# Use the official OpenJDK 17 base image
FROM openjdk:17-jdk-slim

RUN rm -f scylladb-0.0.1-SNAPSHOT.jar
RUN rm -f /usr/app/scylladb-0.0.1-SNAPSHOT.jar

# Copy the JAR file into the image
COPY scylladb-0.0.1-SNAPSHOT.jar /usr/app/scylladb-0.0.1-SNAPSHOT.jar

# Set the working directory
WORKDIR /usr/app

# Command to run the application
ENTRYPOINT ["java", "-Duser.timezone=Asia/Seoul", "-jar", "scylladb-0.0.1-SNAPSHOT.jar"]