# ----------------------------------------------------------
# Spring Boot Config
# ----------------------------------------------------------
spring:
  application:
    name: Scylla Spring Boot
  main:
    banner-mode: 'OFF'
  reactor:
    debug-agent:
      enabled: true
  cassandra:
    schema-action: create_if_not_exists
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: .apps.googleusercontent.com
            client-secret: GOCSPX-
            scope:
              - profile
              - email
          github:
            client-id:
            client-secret:
            scope:
              - read:user
              - user:email
          naver:
            client-name: Naver
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-name: Kakao
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
              - profile_image

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# The HTTP port that the REST controller will listen to.
server:
  port: 8080
  address: 0.0.0.0
  frontend: http://localhost:3000

logging:
  level:
    #    root: debug
    org.springframework.security.web.authentication.logout.LogoutFilter: ERROR
    org:
      springframework:
        security: debug

scylla:
  contactPoints: scylla-node1,scylla-node2
  #  port: 9042
  localDC: datacenter1
  username: cassandra # default
  password: cassandra # default
  keyspace: key
#  consistency: LOCAL_QUORUM